-- ==============================================================================
-- Migration: 20260909185016_manual_booking_sms_ticket_delivery.sql
-- Description: Automatic SMS ticket-link delivery for manually created
--              carrier bookings, via OSON SMS. Transactional outbox +
--              atomic claim RPC + atomic cost-cap reservation RPC +
--              reconciliation-required status for unresolvable duplicates.
-- Project: POPUTKI.ONLINE
--
-- CONSOLIDATION NOTE: this single migration replaces four local files that
-- were superseded before ever being applied or pushed:
--   1. 20260908_manual_booking_sms_outbox.sql
--   2. 20260909_manual_booking_sms_atomic_cap_rpc.sql        (superseded by #3
--      below before it was ever applied anywhere — see "why no intermediate
--      cap version" below)
--   3. 20260910_manual_booking_sms_cap_reservation.sql
--   4. 20260909174859_manual_booking_sms_reconciliation_required.sql
-- All four were confirmed, before this consolidation, to be absent from
-- origin/main, absent from this repo's git history on any branch reachable
-- from origin/main, and absent from production Supabase's applied migration
-- history (production's latest applied migration at the time of this check
-- was 20260906200433_20260906_bus_trip_change_outbox; nothing from this
-- feature had ever been applied). There was therefore no published state to
-- preserve, and no risk in replacing four never-applied files with one.
--
-- This file's timestamp (20260909185016) was generated by the Supabase CLI
-- (`supabase migration new manual_booking_sms_ticket_delivery`), not
-- invented by hand, following this repository's own established convention
-- (see e.g. 20260904130756_acquisition_passenger_funnel_schema.sql) of
-- CLI-assigned 14-digit timestamps, mirrored byte-identically between
-- docs/migrations/ and supabase/migrations/.
--
-- Why no intermediate cap version: the original #2 above had a real,
-- proven concurrency bug (see docs/oson-sms-audit-report.md,
-- "Cap-check atomicity bug") — it serialized the COUNT but reserved
-- nothing, so two concurrent workers evaluating two DIFFERENT outbox rows
-- could both observe "allowed" under daily_cap=1. That bug was found,
-- fixed, and proven fixed via live PostgreSQL testing entirely before any
-- version of this migration was ever applied to any real database
-- (production or otherwise) — so the buggy intermediate signature never
-- had a production existence to be compatible with. Only the corrected,
-- final fn_oson_sms_check_cap(p_outbox_id, ...) signature appears below.
--
-- Design notes (carried forward from the original four files):
--   - Purely additive: creates one new table + two new RPCs. Does not alter
--     bus_ticket_bookings, booking_notifications, booking_claim_sessions,
--     or bus_ticket_notification_outbox. Zero blast radius on existing
--     Telegram/WhatsApp routing, the trip-change outbox, or the
--     claim/handoff flow.
--   - Modeled on the already-production-proven worker pattern in
--     bus_ticket_notification_outbox / fn_claim_bus_trip_notification_batch
--     (FOR UPDATE SKIP LOCKED, lease + processing_token).
--   - Deliberately does NOT store the passenger's full phone number — only
--     a masked copy for audit/display; the live phone is read from
--     bus_ticket_bookings.phone at send time by the service-role worker.
--   - Does NOT store the raw claim/deep-link token, only its SHA-256 hash.
--   - reconciliation_required: for the HTTP 409/duplicate-txn_id case where
--     no provider msg_id is durably known for the row, so the confirmed
--     contract's query_sms.php (login+txn_id+msg_id) cannot be safely
--     called. A row in this status is never auto-claimed (excluded by
--     fn_claim_manual_booking_sms_batch's WHERE clause by construction, not
--     by a separate exclusion rule), never auto-retried, never marked
--     sent/delivered automatically. An operator resolves it manually via
--     OSON's own dashboard/support. See docs/oson-sms-audit-report.md,
--     "Duplicate Reconciliation Correction".
--
-- NOT APPLIED TO PRODUCTION.
-- ==============================================================================

BEGIN;

-- ------------------------------------------------------------------------
-- (a) Table, types, constraints, indexes — final shape, created directly.
-- ------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.manual_booking_sms_outbox (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id INTEGER NOT NULL REFERENCES public.bus_ticket_bookings(id) ON DELETE CASCADE,
    recipient_role TEXT NOT NULL DEFAULT 'passenger'
        CHECK (recipient_role IN ('passenger', 'family_or_group', 'coordinator')),
    channel TEXT NOT NULL DEFAULT 'sms' CHECK (channel = 'sms'),
    recipient_phone_masked TEXT NULL,
    recipient_phone_hmac TEXT NULL,
    carrier_id INTEGER NULL REFERENCES public.users(id) ON DELETE SET NULL,
    template_code TEXT NOT NULL DEFAULT 'manual_booking_ticket_link_v1',
    locale TEXT NOT NULL DEFAULT 'ru' CHECK (locale IN ('ru', 'tj', 'uz')),
    claim_token_hash TEXT NULL,
    idempotency_key TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN (
            'pending', 'processing', 'sent', 'delivered', 'failed',
            'retry', 'dead_letter', 'cancelled', 'reconciliation_required'
        )),
    provider_message_id TEXT NULL,
    attempts_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    scheduled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processing_token TEXT NULL,
    processing_started_at TIMESTAMPTZ NULL,
    lease_expires_at TIMESTAMPTZ NULL,
    cap_reserved_at TIMESTAMPTZ NULL,
    last_error_code TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at TIMESTAMPTZ NULL,
    delivered_at TIMESTAMPTZ NULL,
    cancelled_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_manual_booking_sms_outbox_idempotency_key UNIQUE (idempotency_key)
);

COMMENT ON TABLE public.manual_booking_sms_outbox IS
    'Transactional outbox for automatic SMS ticket-link delivery on manually created carrier bookings (OSON SMS). One row max per (booking, template_code) via idempotency_key.';
COMMENT ON COLUMN public.manual_booking_sms_outbox.recipient_phone_masked IS
    'Masked only (e.g. 9922****789). Full phone is never stored here; read live from bus_ticket_bookings.phone at send time.';
COMMENT ON COLUMN public.manual_booking_sms_outbox.claim_token_hash IS
    'SHA-256 of the raw claim token used in the /t/<token> link, for audit correlation only. Raw token is never persisted here.';
COMMENT ON COLUMN public.manual_booking_sms_outbox.recipient_phone_hmac IS
    'HMAC-SHA256(phone, OSON_SMS_PHONE_HASH_SECRET). Non-reversible without the server secret. Exists ONLY so the worker can group/count sends per phone number for the per-phone daily cap without keeping a second copy of the plaintext phone at rest.';
COMMENT ON COLUMN public.manual_booking_sms_outbox.cap_reserved_at IS
    'Set atomically by fn_oson_sms_check_cap the moment a send is approved against the daily/per-phone/per-carrier caps, so a concurrent worker checking a DIFFERENT row sees this slot as already taken even before this row reaches status=sent.';
-- (e) reconciliation_required — see fn_oson_sms_check_cap / fn_claim_manual_booking_sms_batch
-- above for how it's produced and excluded; this comment documents the status value itself,
-- folded directly into the CHECK constraint above rather than added via a later ALTER.
COMMENT ON COLUMN public.manual_booking_sms_outbox.status IS
    'reconciliation_required: HTTP 409/duplicate received from OSON with no msg_id durably known for this row — never auto-retried, never auto-claimed, never marked sent/delivered automatically. Requires a human to check OSON''s own dashboard/support and resolve manually.';

CREATE INDEX IF NOT EXISTS idx_manual_booking_sms_outbox_status_claim
    ON public.manual_booking_sms_outbox(status, scheduled_at)
    WHERE status IN ('pending', 'processing', 'retry');

CREATE INDEX IF NOT EXISTS idx_manual_booking_sms_outbox_booking_id
    ON public.manual_booking_sms_outbox(booking_id);

CREATE INDEX IF NOT EXISTS idx_manual_booking_sms_outbox_phone_hmac_sent
    ON public.manual_booking_sms_outbox(recipient_phone_hmac, sent_at)
    WHERE status IN ('sent', 'delivered');

CREATE INDEX IF NOT EXISTS idx_manual_booking_sms_outbox_carrier_sent
    ON public.manual_booking_sms_outbox(carrier_id, sent_at)
    WHERE status IN ('sent', 'delivered');

-- ------------------------------------------------------------------------
-- (b) RLS and grants — table-level.
-- ------------------------------------------------------------------------

ALTER TABLE public.manual_booking_sms_outbox ENABLE ROW LEVEL SECURITY;

-- Service-role only. This table can carry masked-but-still-sensitive
-- delivery metadata (provider message IDs, error codes); carriers and
-- anon/authenticated roles have no legitimate reason to read it directly —
-- carrier-facing status is exposed via a dedicated admin-safe projection in
-- application code, not direct table access. No RLS policy is created:
-- with zero policies and RLS enabled, only a role that bypasses RLS
-- (service_role) can read/write regardless of any future GRANT.
REVOKE ALL ON TABLE public.manual_booking_sms_outbox FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.manual_booking_sms_outbox TO service_role;

-- ------------------------------------------------------------------------
-- (c) Claim RPC — atomic FOR UPDATE SKIP LOCKED + lease.
-- ------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_claim_manual_booking_sms_batch(
    p_batch_size INTEGER DEFAULT 10,
    p_worker_token TEXT DEFAULT gen_random_uuid()::text,
    p_lease_seconds INTEGER DEFAULT 60
)
RETURNS TABLE (
    outbox_id UUID,
    booking_id INTEGER,
    recipient_role TEXT,
    carrier_id INTEGER,
    template_code TEXT,
    locale TEXT,
    idempotency_key TEXT,
    attempts_count INTEGER,
    max_attempts INTEGER,
    processing_token TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER -- required: callers (service-role worker) claim/update rows
                  -- across the whole table under FOR UPDATE SKIP LOCKED,
                  -- which must run with the function owner's privileges,
                  -- not the (already service_role-only, RLS-gated) caller's.
SET search_path = public, pg_temp
AS $$
DECLARE
    v_now TIMESTAMPTZ := NOW();
    v_lease_expiry TIMESTAMPTZ := v_now + (p_lease_seconds || ' seconds')::interval;
BEGIN
    RETURN QUERY
    WITH candidate_records AS (
        SELECT o.id
        FROM public.manual_booking_sms_outbox o
        WHERE (
                (o.status IN ('pending', 'retry') AND o.scheduled_at <= v_now)
                OR (o.status = 'processing' AND o.lease_expires_at < v_now)
              )
          AND o.attempts_count < o.max_attempts
        ORDER BY o.scheduled_at ASC
        LIMIT p_batch_size
        FOR UPDATE SKIP LOCKED
    ),
    claimed_records AS (
        UPDATE public.manual_booking_sms_outbox o
        SET
            status = 'processing',
            processing_token = p_worker_token,
            processing_started_at = v_now,
            lease_expires_at = v_lease_expiry,
            attempts_count = o.attempts_count + 1
        FROM candidate_records c
        WHERE o.id = c.id
        RETURNING
            o.id, o.booking_id, o.recipient_role, o.carrier_id, o.template_code, o.locale,
            o.idempotency_key, o.attempts_count, o.max_attempts, o.processing_token
    )
    SELECT
        cr.id AS outbox_id, cr.booking_id, cr.recipient_role, cr.carrier_id, cr.template_code,
        cr.locale, cr.idempotency_key, cr.attempts_count, cr.max_attempts, cr.processing_token
    FROM claimed_records cr;
END;
$$;

REVOKE ALL ON FUNCTION public.fn_claim_manual_booking_sms_batch FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_claim_manual_booking_sms_batch TO service_role;

-- ------------------------------------------------------------------------
-- (d) Atomic cost-cap reservation RPC — final, corrected signature only.
-- ------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_oson_sms_check_cap(
    p_outbox_id UUID,
    p_phone_hmac TEXT,
    p_carrier_id INTEGER,
    p_daily_cap INTEGER,
    p_per_phone_cap INTEGER,
    p_per_carrier_cap INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER -- required: pg_advisory_xact_lock + the cap_reserved_at
                  -- write must be atomic and visible to every concurrent
                  -- caller regardless of session; this is a service-role
                  -- worker-only RPC, never exposed to anon/authenticated.
SET search_path = public, pg_temp
AS $$
DECLARE
    v_lock_key BIGINT := ('x' || substr(md5('oson_sms_daily_cap'), 1, 16))::bit(64)::bigint;
    v_since TIMESTAMPTZ := date_trunc('day', NOW());
    v_global_count INTEGER;
    v_phone_count INTEGER;
    v_carrier_count INTEGER;
BEGIN
    -- Serializes this whole check-and-reserve across ALL concurrent callers
    -- (any worker process, any connection) for the duration of this
    -- transaction. Released automatically at transaction end.
    PERFORM pg_advisory_xact_lock(v_lock_key);

    IF p_daily_cap IS NULL OR p_daily_cap <= 0 THEN
        RETURN jsonb_build_object('allowed', false, 'reason', 'DAILY_CAP_NOT_CONFIGURED');
    END IF;

    -- A slot counts as taken whether it has already been sent/delivered OR
    -- was reserved by a concurrent/prior call still in flight today.
    SELECT COUNT(*) INTO v_global_count
    FROM public.manual_booking_sms_outbox
    WHERE (status IN ('sent', 'delivered') AND sent_at >= v_since)
       OR (cap_reserved_at IS NOT NULL AND cap_reserved_at >= v_since);

    IF v_global_count >= p_daily_cap THEN
        RETURN jsonb_build_object('allowed', false, 'reason', 'DAILY_CAP_EXCEEDED');
    END IF;

    IF p_phone_hmac IS NOT NULL THEN
        SELECT COUNT(*) INTO v_phone_count
        FROM public.manual_booking_sms_outbox
        WHERE recipient_phone_hmac = p_phone_hmac
          AND (
              (status IN ('sent', 'delivered') AND sent_at >= v_since)
              OR (cap_reserved_at IS NOT NULL AND cap_reserved_at >= v_since)
          );

        IF v_phone_count >= COALESCE(p_per_phone_cap, 1) THEN
            RETURN jsonb_build_object('allowed', false, 'reason', 'PER_PHONE_DAILY_CAP_EXCEEDED');
        END IF;
    END IF;

    IF p_carrier_id IS NOT NULL AND p_per_carrier_cap IS NOT NULL AND p_per_carrier_cap > 0 THEN
        SELECT COUNT(*) INTO v_carrier_count
        FROM public.manual_booking_sms_outbox
        WHERE carrier_id = p_carrier_id
          AND (
              (status IN ('sent', 'delivered') AND sent_at >= v_since)
              OR (cap_reserved_at IS NOT NULL AND cap_reserved_at >= v_since)
          );

        IF v_carrier_count >= p_per_carrier_cap THEN
            RETURN jsonb_build_object('allowed', false, 'reason', 'PER_CARRIER_DAILY_CAP_EXCEEDED');
        END IF;
    END IF;

    IF p_outbox_id IS NOT NULL THEN
        UPDATE public.manual_booking_sms_outbox
        SET cap_reserved_at = NOW()
        WHERE id = p_outbox_id;
    END IF;

    RETURN jsonb_build_object('allowed', true);
END;
$$;

REVOKE ALL ON FUNCTION public.fn_oson_sms_check_cap(UUID, TEXT, INTEGER, INTEGER, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_oson_sms_check_cap(UUID, TEXT, INTEGER, INTEGER, INTEGER, INTEGER) TO service_role;

COMMIT;
